package model.VO;

import oracle.jbo.RowSet;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Mar 26 10:41:49 EEST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GroupDetailForAddViewRowImpl extends ViewRowImpl {
    public static final int ENTITY_GROUPDETAILFORADD = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Id,
        GroupId,
        RoleName,
        RoleStatus,
        ProgramNconversionsRoleStatus1,
        StaticUserRoleForGetView1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ID = AttributesEnum.Id.index();
    public static final int GROUPID = AttributesEnum.GroupId.index();
    public static final int ROLENAME = AttributesEnum.RoleName.index();
    public static final int ROLESTATUS = AttributesEnum.RoleStatus.index();
    public static final int PROGRAMNCONVERSIONSROLESTATUS1 = AttributesEnum.ProgramNconversionsRoleStatus1.index();
    public static final int STATICUSERROLEFORGETVIEW1 = AttributesEnum.StaticUserRoleForGetView1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public GroupDetailForAddViewRowImpl() {
    }

    /**
     * Gets GroupDetailForAdd entity object.
     * @return the GroupDetailForAdd
     */
    public EntityImpl getGroupDetailForAdd() {
        return (EntityImpl) getEntity(ENTITY_GROUPDETAILFORADD);
    }

    /**
     * Gets the attribute value for ID using the alias name Id.
     * @return the ID
     */
    public Integer getId() {
        return (Integer) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name Id.
     * @param value value to set the ID
     */
    public void setId(Integer value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for GROUP_ID using the alias name GroupId.
     * @return the GROUP_ID
     */
    public Integer getGroupId() {
        return (Integer) getAttributeInternal(GROUPID);
    }

    /**
     * Sets <code>value</code> as attribute value for GROUP_ID using the alias name GroupId.
     * @param value value to set the GROUP_ID
     */
    public void setGroupId(Integer value) {
        setAttributeInternal(GROUPID, value);
    }

    /**
     * Gets the attribute value for ROLE_NAME using the alias name RoleName.
     * @return the ROLE_NAME
     */
    public String getRoleName() {
        return (String) getAttributeInternal(ROLENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for ROLE_NAME using the alias name RoleName.
     * @param value value to set the ROLE_NAME
     */
    public void setRoleName(String value) {
        setAttributeInternal(ROLENAME, value);
    }

    /**
     * Gets the attribute value for ROLE_STATUS using the alias name RoleStatus.
     * @return the ROLE_STATUS
     */
    public Integer getRoleStatus() {
        return (Integer) getAttributeInternal(ROLESTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for ROLE_STATUS using the alias name RoleStatus.
     * @param value value to set the ROLE_STATUS
     */
    public void setRoleStatus(Integer value) {
        setAttributeInternal(ROLESTATUS, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ProgramNconversionsRoleStatus1.
     */
    public RowSet getProgramNconversionsRoleStatus1() {
        return (RowSet) getAttributeInternal(PROGRAMNCONVERSIONSROLESTATUS1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> StaticUserRoleForGetView1.
     */
    public RowSet getStaticUserRoleForGetView1() {
        return (RowSet) getAttributeInternal(STATICUSERROLEFORGETVIEW1);
    }
}

