package model.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Mar 26 10:41:50 EEST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GroupDetailForAddViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public GroupDetailForAddViewImpl() {
    }
}

