package model.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Mar 13 02:50:14 EET 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StaticUserRoleForGetViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public StaticUserRoleForGetViewImpl() {
    }
}

