package model.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 11 02:10:23 EET 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UserRoleForMTFRenderViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public UserRoleForMTFRenderViewImpl() {
    }
}

